RUN docker pull ghcr.io/puppeteer/puppeteer:21.5.2

# RUN npm i chromium-browser

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable

WORKDIR /usr/src/app


COPY package*.json ./
RUN npm ci
COPY . .
CMD ["node", "index.js"]